var NAVTREE_DATA =
[ [ "android.app", "reference/android/app/package-summary.html", [ [ "Classes", null, [ [ "AndroidAppHelper", "reference/android/app/AndroidAppHelper.html", null, "" ] ]
, null ] ]
, "" ], [ "android.content.res", "reference/android/content/res/package-summary.html", [ [ "Classes", null, [ [ "XModuleResources", "reference/android/content/res/XModuleResources.html", null, "" ], [ "XResForwarder", "reference/android/content/res/XResForwarder.html", null, "" ], [ "XResources", "reference/android/content/res/XResources.html", null, "" ], [ "XResources.DimensionReplacement", "reference/android/content/res/XResources.DimensionReplacement.html", null, "50" ], [ "XResources.DrawableLoader", "reference/android/content/res/XResources.DrawableLoader.html", null, "" ], [ "XResources.ResourceNames", "reference/android/content/res/XResources.ResourceNames.html", null, "" ] ]
, null ] ]
, "" ], [ "de.robv.android.xposed", "reference/de/robv/android/xposed/package-summary.html", [ [ "Interfaces", null, [ [ "IXposedHookInitPackageResources", "reference/de/robv/android/xposed/IXposedHookInitPackageResources.html", null, "" ], [ "IXposedHookLoadPackage", "reference/de/robv/android/xposed/IXposedHookLoadPackage.html", null, "" ], [ "IXposedHookZygoteInit", "reference/de/robv/android/xposed/IXposedHookZygoteInit.html", null, "" ] ]
, null ], [ "Classes", null, [ [ "IXposedHookZygoteInit.StartupParam", "reference/de/robv/android/xposed/IXposedHookZygoteInit.StartupParam.html", null, "" ], [ "SELinuxHelper", "reference/de/robv/android/xposed/SELinuxHelper.html", null, "60" ], [ "XC_MethodHook", "reference/de/robv/android/xposed/XC_MethodHook.html", null, "" ], [ "XC_MethodHook.MethodHookParam", "reference/de/robv/android/xposed/XC_MethodHook.MethodHookParam.html", null, "" ], [ "XC_MethodHook.Unhook", "reference/de/robv/android/xposed/XC_MethodHook.Unhook.html", null, "" ], [ "XC_MethodReplacement", "reference/de/robv/android/xposed/XC_MethodReplacement.html", null, "" ], [ "XposedBridge", "reference/de/robv/android/xposed/XposedBridge.html", null, "" ], [ "XposedHelpers", "reference/de/robv/android/xposed/XposedHelpers.html", null, "" ], [ "XSharedPreferences", "reference/de/robv/android/xposed/XSharedPreferences.html", null, "" ] ]
, null ], [ "Errors", null, [ [ "XposedHelpers.ClassNotFoundError", "reference/de/robv/android/xposed/XposedHelpers.ClassNotFoundError.html", null, "" ], [ "XposedHelpers.InvocationTargetError", "reference/de/robv/android/xposed/XposedHelpers.InvocationTargetError.html", null, "" ] ]
, null ] ]
, "" ], [ "de.robv.android.xposed.callbacks", "reference/de/robv/android/xposed/callbacks/package-summary.html", [ [ "Interfaces", null, [ [ "IXUnhook", "reference/de/robv/android/xposed/callbacks/IXUnhook.html", null, "" ] ]
, null ], [ "Classes", null, [ [ "XC_InitPackageResources", "reference/de/robv/android/xposed/callbacks/XC_InitPackageResources.html", null, "" ], [ "XC_InitPackageResources.InitPackageResourcesParam", "reference/de/robv/android/xposed/callbacks/XC_InitPackageResources.InitPackageResourcesParam.html", null, "" ], [ "XC_LayoutInflated", "reference/de/robv/android/xposed/callbacks/XC_LayoutInflated.html", null, "" ], [ "XC_LayoutInflated.LayoutInflatedParam", "reference/de/robv/android/xposed/callbacks/XC_LayoutInflated.LayoutInflatedParam.html", null, "" ], [ "XC_LayoutInflated.Unhook", "reference/de/robv/android/xposed/callbacks/XC_LayoutInflated.Unhook.html", null, "" ], [ "XC_LoadPackage", "reference/de/robv/android/xposed/callbacks/XC_LoadPackage.html", null, "" ], [ "XC_LoadPackage.LoadPackageParam", "reference/de/robv/android/xposed/callbacks/XC_LoadPackage.LoadPackageParam.html", null, "" ], [ "XCallback", "reference/de/robv/android/xposed/callbacks/XCallback.html", null, "" ], [ "XCallback.Param", "reference/de/robv/android/xposed/callbacks/XCallback.Param.html", null, "" ] ]
, null ] ]
, "" ], [ "de.robv.android.xposed.services", "reference/de/robv/android/xposed/services/package-summary.html", [ [ "Classes", null, [ [ "BaseService", "reference/de/robv/android/xposed/services/BaseService.html", null, "60" ], [ "FileResult", "reference/de/robv/android/xposed/services/FileResult.html", null, "60" ] ]
, null ] ]
, "60" ] ]

;
